### ISSUE TITLE
unable to interact with menu in fullscreen application

### ISSUE THREAD

**Issue by xiv1337** [Rebzzel/kiero#53]
title pretty much says it all

**Comment by Rebzzel** [comment]
Any information?

**Comment by xiv1337** [comment]
when im running an application in fullscreen i can see the menu however i cannot interact with it (clicking etc)

but if i run the application in borderless it is completely fine

**Comment by Rebzzel** [comment]
So you using imgui example?

**Comment by xiv1337** [comment]
no- when i inject the dll into my targeted process

**Comment by Rebzzel** [comment]
If you can't explain how this is related to kiero, then why open a issue?

Okay, I'll try to help you understand. 
Kiero is a graphical hook, and it has nothing to do with UI and other stuff. 
If you don't use the code from the ImGui example, then the problem is in your code.

If you really want to figure out what the problem is, you should first post your code.

**Comment by xiv1337** [comment]
I also tried with just this repository and the issue remained- I personally am not bothered about it but thought i should atleast open an issue as it may have been something that you werent aware of.

**Comment by Rebzzel** [comment]
I don't even understand what you're talking about :\
