### ISSUE TITLE
making http requests on a seaprate thread

### ISSUE THREAD

**Issue by ughstudios** [Rebzzel/kiero#54]
I want to make http requests using libcurl and use the data I get back to display it using ImGUI. When I do this, it just hangs the entire application. Is there a best practice for this?

**Comment by Rebzzel** [comment]
Firstly, it is not related to kiero. So I will close this topic right away. 
There is a https://stackoverflow.com for such questions.

Secondly, you haven't provided any code to figure out what your problem is.
The only thing I can give you - make sure that you make the request in a separate thread from the render thread.

Have a nice day!
